### ISSUE TITLE
Incompatibility with Epic Fight mod

### ISSUE THREAD

**Issue by sirben99** [YUNG-GANG/YUNGs-Better-Portals#1]
Hey!

The world doesent load and console says errors, when Better Portals and EpicFigth mod are installed (https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod)

Forge: Latest 1.16.5
Mod versions: Both latest

I have a log attacht to this issue
[latest.log](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/5943655/latest.log)

**Comment by yungnickyoung** [comment]
Well, it's hard for me to debug this since that mod isn't open source.

**Comment by sirben99** [comment]
> Well, it's hard for me to debug this since that mod isn't open source.

I have made a issue on EpicFight mod page: https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/issues/17

Sorry forgot to link that. Most likely the problem is on Epics authors side, but im not sure either

**Comment by sirben99** [comment]
Update: I got an answer from the mod creator, and he sayd that he probably found a solution for the problem. Ill test the update when it comes and report back to here and there.

**Comment by yungnickyoung** [comment]
Try v0.3.1 to see if it fixes this issue for you.

**Comment by sirben99** [comment]
> Try v0.3.1 to see if it fixes this issue for you.

Hey!

I tested it and got no crashes. Everything works fine now. Thank you!
