### ISSUE TITLE
Crash on first world load related to a structure from this mod generating

### ISSUE THREAD

**Issue by Corvus20** [YUNG-GANG/YUNGs-Better-Portals#11]
Might be a conflict/issue with terraforged, but being that it mentioned a structure from your mod in the crash logs, I figured this would be the place to report it.

[crash-2021-02-18_16.46.55-client.txt](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/6006103/crash-2021-02-18_16.46.55-client.txt)

**Comment by yungnickyoung** [comment]
Hey, please upload the file to a pastebin or gist.

**Comment by ProsperCraft** [comment]
Dedicated server crash - https://gist.github.com/ProsperCraft/f0c7d7635d7e8461f26282f0428853ca

**Comment by Corvus20** [comment]
Updated forge and it fixed, I'll close this.
