### ISSUE TITLE
Rift structure generation issue

### ISSUE THREAD

**Issue by Spleenczar** [YUNG-GANG/YUNGs-Better-Portals#12]
Unsure if this is a conflict or a bug with Better Portals, but many of the portal structures are spawning half-missing across chunk borders.
![2021-02-20_18 34 34](https://user-images.githubusercontent.com/18106048/108611220-720cad00-73aa-11eb-85dd-eea0e33f3928.png)
![2021-02-20_18 34 15](https://user-images.githubusercontent.com/18106048/108611223-76d16100-73aa-11eb-97ec-e4de39099b6b.png)
I'm running Terraforged, Better Caves, Quark, and BoP among other things. Can provide a modlist/logs if necessary.

**Comment by yungnickyoung** [comment]
Looks like this is happening in the middle of a Quark mega cave. These are notorious for messing up other structures. Try disabling those, as well as the Quark crevices.

**Comment by Spleenczar** [comment]
Alright, thanks, was assuming the cave was from Better Caves because I didn't realize that Quark had those. Seems to be the cause of it since I don't see them messed up outside of that area.
