### ISSUE TITLE
Causes Ticking Entity error in Transport Module Configurator

### ISSUE THREAD

**Issue by czbuendel** [YUNG-GANG/YUNGs-Better-Portals#14]
When installed with Transport loading a cart into the Module Configurator will cause the instance to freeze requiring a force quit. Checking the log files gives a ticking entity error, which I have attached. https://pastebin.com/EpF72Jzc

Tried in an instance with just Transport and Better Portals (and their dependencies) to confirm the issue.
Forge 36.0.14 (tried with most up to date 36.0.42 as well, still causes the error)
Transport 1.16.4-3.4.2
Better Portals 1.16.4-0.3

The issue does not exist with Better Portals 1.16.4-0.2.1.

BrassGoggledCoders/Transport#34

**Comment by SkySom** [comment]
Heyo, Transport dev here. I'd generally suggestion not calling getCapability().isPresent() in the Attach Event as that is during the constructor of Entity, and thus happens before initialization of an Entity has completed. You're better off always attaching and if an Entity returns it, it'll return long before it gets to the attached version.

**Comment by yungnickyoung** [comment]
@SkySom I appreciate the info. I added that in recently because of capability-related crashes that have been happening when using other mods that also attach capabilities, but it didn't solve anything. I'll go ahead and remove it, although I suspect the crashes will continue until I figure out the source of the issue.

**Comment by yungnickyoung** [comment]
Try v0.3.1 to see if it fixes this issue for you.

**Comment by czbuendel** [comment]
Updated to 0.3.1 and can load a cart into the Module Configurator again. Thanks again!
