### ISSUE TITLE
Blame Report 1.9.2

### ISSUE THREAD

**Issue by ghost** [YUNG-GANG/YUNGs-Better-Portals#16]
This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "betterportals:monolith"
    },
    "decorator": {
      "config": {
        "count": 1
      },
      "type": "minecraft:count_multilayer"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [minecraft:snowy_taiga_mountains, minecraft:giant_tree_taiga_hills, minecraft:frozen_ocean, minecraft:savanna_plateau, atmospheric:rainforest_mountains, minecraft:taiga, minecraft:taiga_hills,
                   minecraft:wooded_mountains, minecraft:jungle_edge, minecraft:modified_gravelly_mountains, minecraft:savanna, minecraft:swamp, minecraft:giant_tree_taiga, atmospheric:sparse_rainforest_basin,
                   minecraft:ice_spikes, minecraft:desert_hills, minecraft:snowy_taiga_hills, minecraft:crimson_forest, minecraft:dark_forest, minecraft:jungle_hills, minecraft:mushroom_field_shore,
                   minecraft:snowy_tundra, minecraft:frozen_river, minecraft:lukewarm_ocean, atmospheric:rainforest, minecraft:mushroom_fields, minecraft:warm_ocean, minecraft:giant_spruce_taiga,
                   minecraft:forest, minecraft:end_midlands, minecraft:deep_ocean, minecraft:sunflower_plains, minecraft:gravelly_mountains, atmospheric:rocky_dunes, autumnity:pumpkin_fields,
                   minecraft:nether_wastes, minecraft:flower_forest, minecraft:deep_lukewarm_ocean, atmospheric:flourishing_dunes, desolation:charred_forest, minecraft:shattered_savanna_plateau, minecraft:snowy_taiga,
                   minecraft:desert, minecraft:beach, minecraft:mountain_edge, minecraft:deep_frozen_ocean, minecraft:river, endergetic:poise_forest, minecraft:the_void,
                   atmospheric:dunes_hills, atmospheric:dunes, autumnity:maple_forest_hills, minecraft:wooded_hills, minecraft:deep_cold_ocean, minecraft:stone_shore, minecraft:shattered_savanna,
                   minecraft:bamboo_jungle_hills, minecraft:tall_birch_forest, minecraft:end_highlands, atmospheric:sparse_rainforest_plateau, minecraft:modified_wooded_badlands_plateau, atmospheric:rainforest_plateau, minecraft:eroded_badlands,
                   minecraft:desert_lakes, minecraft:bamboo_jungle, minecraft:plains, minecraft:dark_forest_hills, minecraft:end_barrens, minecraft:birch_forest_hills, minecraft:modified_badlands_plateau,
                   minecraft:small_end_islands, minecraft:the_end, minecraft:badlands_plateau, minecraft:taiga_mountains, minecraft:snowy_beach, minecraft:modified_jungle_edge, autumnity:maple_forest,
                   minecraft:giant_spruce_taiga_hills, atmospheric:rainforest_basin, minecraft:swamp_hills, minecraft:jungle, minecraft:birch_forest, minecraft:ocean, minecraft:mountains,
                   minecraft:cold_ocean, minecraft:soul_sand_valley, minecraft:warped_forest, atmospheric:rocky_dunes_hills, atmospheric:petrified_dunes, minecraft:badlands, minecraft:wooded_badlands_plateau,
                   minecraft:modified_jungle, minecraft:tall_birch_hills, minecraft:snowy_mountains, minecraft:deep_warm_ocean]

**Comment by ghost** [comment]
### Other variant that also appeared:
 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "betterportals:portal_lake"
    },
    "decorator": {
      "config": {},
      "type": "betterportals:portal_lake"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [minecraft:snowy_taiga_mountains, minecraft:giant_tree_taiga_hills, minecraft:frozen_ocean, minecraft:savanna_plateau, atmospheric:rainforest_mountains, minecraft:taiga, minecraft:taiga_hills,
                   minecraft:wooded_mountains, minecraft:jungle_edge, minecraft:modified_gravelly_mountains, minecraft:savanna, minecraft:swamp, minecraft:giant_tree_taiga, minecraft:basalt_deltas,
                   atmospheric:sparse_rainforest_basin, minecraft:ice_spikes, minecraft:desert_hills, minecraft:snowy_taiga_hills, minecraft:crimson_forest, minecraft:dark_forest, minecraft:jungle_hills,
                   minecraft:mushroom_field_shore, minecraft:snowy_tundra, minecraft:frozen_river, minecraft:lukewarm_ocean, atmospheric:rainforest, minecraft:mushroom_fields, minecraft:warm_ocean,
                   minecraft:giant_spruce_taiga, minecraft:forest, minecraft:end_midlands, minecraft:deep_ocean, minecraft:sunflower_plains, minecraft:gravelly_mountains, atmospheric:rocky_dunes,
                   autumnity:pumpkin_fields, minecraft:nether_wastes, minecraft:flower_forest, minecraft:deep_lukewarm_ocean, atmospheric:flourishing_dunes, desolation:charred_forest, minecraft:shattered_savanna_plateau,
                   minecraft:snowy_taiga, minecraft:desert, minecraft:beach, minecraft:mountain_edge, minecraft:deep_frozen_ocean, minecraft:river, endergetic:poise_forest,
                   minecraft:the_void, atmospheric:dunes_hills, atmospheric:dunes, autumnity:maple_forest_hills, minecraft:wooded_hills, minecraft:deep_cold_ocean, minecraft:stone_shore,
                   minecraft:shattered_savanna, minecraft:bamboo_jungle_hills, minecraft:tall_birch_forest, minecraft:end_highlands, atmospheric:sparse_rainforest_plateau, minecraft:modified_wooded_badlands_plateau, atmospheric:rainforest_plateau,
                   minecraft:eroded_badlands, minecraft:desert_lakes, minecraft:bamboo_jungle, minecraft:plains, minecraft:dark_forest_hills, minecraft:end_barrens, minecraft:birch_forest_hills,
                   minecraft:modified_badlands_plateau, minecraft:small_end_islands, minecraft:the_end, minecraft:badlands_plateau, minecraft:taiga_mountains, minecraft:snowy_beach, minecraft:modified_jungle_edge,
                   autumnity:maple_forest, minecraft:giant_spruce_taiga_hills, atmospheric:rainforest_basin, minecraft:swamp_hills, minecraft:jungle, minecraft:birch_forest, minecraft:ocean,
                   minecraft:mountains, minecraft:cold_ocean, minecraft:soul_sand_valley, minecraft:warped_forest, atmospheric:rocky_dunes_hills, atmospheric:petrified_dunes, minecraft:badlands,
                   minecraft:wooded_badlands_plateau, minecraft:modified_jungle, minecraft:tall_birch_hills, minecraft:snowy_mountains, minecraft:deep_warm_ocean]

**Comment by ghost** [comment]
### Other other variant that also appeared:
 This ConfiguredFeature was found to be not registered. Look at the JSON info and try to
 find which mod it belongs to. Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.

 JSON info : {
  "config": {
    "feature": {
      "config": {},
      "type": "betterportals:portal_lake_2"
    },
    "decorator": {
      "config": {},
      "type": "betterportals:portal_lake"
    }
  },
  "type": "minecraft:decorated"
}

 Biome affected : [minecraft:snowy_taiga_mountains, minecraft:giant_tree_taiga_hills, minecraft:frozen_ocean, minecraft:savanna_plateau, atmospheric:rainforest_mountains, minecraft:taiga, minecraft:taiga_hills,
                   minecraft:wooded_mountains, minecraft:jungle_edge, minecraft:modified_gravelly_mountains, minecraft:savanna, minecraft:swamp, minecraft:giant_tree_taiga, minecraft:basalt_deltas,
                   atmospheric:sparse_rainforest_basin, minecraft:ice_spikes, minecraft:desert_hills, minecraft:snowy_taiga_hills, minecraft:crimson_forest, minecraft:dark_forest, minecraft:jungle_hills,
                   minecraft:mushroom_field_shore, minecraft:snowy_tundra, minecraft:frozen_river, minecraft:lukewarm_ocean, atmospheric:rainforest, minecraft:mushroom_fields, minecraft:warm_ocean,
                   minecraft:giant_spruce_taiga, minecraft:forest, minecraft:end_midlands, minecraft:deep_ocean, minecraft:sunflower_plains, minecraft:gravelly_mountains, atmospheric:rocky_dunes,
                   autumnity:pumpkin_fields, minecraft:nether_wastes, minecraft:flower_forest, minecraft:deep_lukewarm_ocean, atmospheric:flourishing_dunes, desolation:charred_forest, minecraft:shattered_savanna_plateau,
                   minecraft:snowy_taiga, minecraft:desert, minecraft:beach, minecraft:mountain_edge, minecraft:deep_frozen_ocean, minecraft:river, endergetic:poise_forest,
                   minecraft:the_void, atmospheric:dunes_hills, atmospheric:dunes, autumnity:maple_forest_hills, minecraft:wooded_hills, minecraft:deep_cold_ocean, minecraft:stone_shore,
                   minecraft:shattered_savanna, minecraft:bamboo_jungle_hills, minecraft:tall_birch_forest, minecraft:end_highlands, atmospheric:sparse_rainforest_plateau, minecraft:modified_wooded_badlands_plateau, atmospheric:rainforest_plateau,
                   minecraft:eroded_badlands, minecraft:desert_lakes, minecraft:bamboo_jungle, minecraft:plains, minecraft:dark_forest_hills, minecraft:end_barrens, minecraft:birch_forest_hills,
                   minecraft:modified_badlands_plateau, minecraft:small_end_islands, minecraft:the_end, minecraft:badlands_plateau, minecraft:taiga_mountains, minecraft:snowy_beach, minecraft:modified_jungle_edge,
                   autumnity:maple_forest, minecraft:giant_spruce_taiga_hills, atmospheric:rainforest_basin, minecraft:swamp_hills, minecraft:jungle, minecraft:birch_forest, minecraft:ocean,
                   minecraft:mountains, minecraft:cold_ocean, minecraft:soul_sand_valley, minecraft:warped_forest, atmospheric:rocky_dunes_hills, atmospheric:petrified_dunes, minecraft:badlands,
                   minecraft:wooded_badlands_plateau, minecraft:modified_jungle, minecraft:tall_birch_hills, minecraft:snowy_mountains, minecraft:deep_warm_ocean]

**Comment by ghost** [comment]
### and lastly:
 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

betterportals:monolith
betterportals:portal_lake
betterportals:portal_lake_2
desolation:ashbramble
desolation:charred_forest_ctd
desolation:charred_forest_lvtd
desolation:charred_forest_tvtd
desolation:charredlog

**Comment by yungnickyoung** [comment]
Thanks for reporting this. Please try v0.3.2 to see if it fixes the issue.

**Comment by ghost** [comment]
yup, now works like a charm! thanks for fixing :)
