### ISSUE TITLE
Crash with Terraforged

### ISSUE THREAD

**Issue by Corvus20** [YUNG-GANG/YUNGs-Better-Portals#19]
Game crashes when trying to place a portal lake, according to the crash log. Can randomly occur when loading new chunks, whether it be the second you load a new world, or 10 minutes into flying around exploring the world.

Crash Log:
[crash-2021-03-21_18.21.46-client.txt](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/6178502/crash-2021-03-21_18.21.46-client.txt)

**Comment by yungnickyoung** [comment]
Seems to be the same root issue as #21. Terraforged likely unrelated.
