### ISSUE TITLE
Add option to reduce the spawn of portals

### ISSUE THREAD

**Issue by Akaruz64** [YUNG-GANG/YUNGs-Better-Portals#2]
Not an issue per se, but i think the portals are spawning too frequently for my taste, would it be possible to add a config option to adjust it and make them more rare? after all, i get like 4 to 5 portals on a single chunk, if not more.

Thanks! and keep up the fine work!

**Comment by yungnickyoung** [comment]
4-5 per chunk!? That's definitely not supposed to happen. Can you post a screenshot?

Also, you can tweak the spawnrate in your `rifts.json` file. See the `betterportals` directory in your config folder for more info.

**Comment by Akaruz64** [comment]
Oh, didn't saw the rift.json config, i'm assuming this line is to change spawn, "spawnChance": 0.15, should i go higher or lower than this number? 

I may have been a bit exaggerated with the amount, didn't actually count them, but still there are too many of them for my taste, since it's an exploration based mode, I would prefer to find one every 20 or 30 chunks, and not so many next to each other, but that's a personal preferences and that's completely fine like this if i can adjust it myself.

https://pasteboard.co/JNwq6iY.png

Thanks for the help!
