### ISSUE TITLE
[1.16.5] Dedicated server crash during PortalLake2 feature placement

### ISSUE THREAD

**Issue by ProsperCraft** [YUNG-GANG/YUNGs-Better-Portals#21]
https://gist.github.com/ProsperCraft/efaab6d5e40c34be23549d69cfe5d140

Modpack - [Towncraft TWO for 1.16.5](https://www.curseforge.com/minecraft/modpacks/towncraft)

It never generated a crash report, after this, it just locked up and I had to kill the process.

**Comment by Gunner76th** [comment]
[crash-2021-04-04_22.00.23-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/6256073/crash-2021-04-04_22.00.23-server.txt)
Here is my Crash Report. Same issue, Engineer's Life 2 by Dreams 
https://www.curseforge.com/minecraft/modpacks/engineers-life-2

**Comment by Gunner76th** [comment]
@ProsperCraft In the future it is best to either supply the crash report, or a COMPLETE latest.log file. Snippets do not always catch the entire issue, as there might be issues elsewhere in the log that you aren't aware of that are related to the crash.

**Comment by yungnickyoung** [comment]
Seems that, for some reason, the crash is happening when trying to fetch the rift variant's `blockSelector`. Double check that your `rifts.json` is configured correctly.

Additionally, the latest.log may prove to be useful, as there may be some warnings or error printed to the console from YUNG's API when reading in the JSON config that may be of use.

**Comment by yungnickyoung** [comment]
I believe this particular crash was addressed in the v0.3.8 release. If the issue persists, please open a new report with a fresh crash report.
