### ISSUE TITLE
NPE crash after falling

### ISSUE THREAD

**Issue by Miner239** [YUNG-GANG/YUNGs-Better-Portals#23]
Crash log: https://paste.ee/p/ODUpu

Crash happens randomly in the overworld. I have never been to the Nether. Distance from a portal seems to not matter since I've also had this crash when I'm on the surface.

**Comment by Miner239** [comment]
It seems like this crash happens occasionally when I fall from a great height.

**Comment by Miner239** [comment]
A new crash that also happened right after taking fall damage, this time on a different function: https://paste.ee/p/sVR2Z (and now it happens in the nether)

**Comment by yungnickyoung** [comment]
The paste seems to have been removed. Was this issue resolved?

**Comment by yungnickyoung** [comment]
Seems to be the same root issue as #20 . Gonna be redirecting all discussion into there.
