### ISSUE TITLE
NPE Crash during PortalLake2 feature placement

### ISSUE THREAD

**Issue by sfiomn** [YUNG-GANG/YUNGs-Better-Portals#26]
Hello there,

I'm using Minecraft Version: 1.16.5 with Forge: net.minecraftforge:36.1.4.

All the details are in the crash report here:
https://gist.github.com/sfiomn/ffcdaf2e50597ddf8d9820493a06fdc3

I encountered the issue after the creation of a new world locally. 
I don't know if this crash can occur in runtime on a server.

If you have a bit of time to investigate on it, would be so great ! Really love the concept of this mod.

Thanks in advance

**Comment by yungnickyoung** [comment]
Seems to be same crash as #21.
