### ISSUE TITLE
[Compat] Aquaculture fish apparently spawn in portal fluid

### ISSUE THREAD

**Issue by lincore81** [YUNG-GANG/YUNGs-Better-Portals#29]
Not sure which mod is to blame here, so I've submitted this issue to both projects (feel free to close). Whenever I enter the nether, I get a dozen aquaculture fish on the other side. No vanilla fish however. I assume they spawn in the portal fluid and immediately teleport.

**Comment by yungnickyoung** [comment]
Seems to have been resolved in https://github.com/TeamMetallurgy/Aquaculture/issues/242
