### ISSUE TITLE
Drank a bucket of milk, and the game crashed

### ISSUE THREAD

**Issue by Darkmega18** [YUNG-GANG/YUNGs-Better-Portals#33]
https://pastebin.com/WwAiJPFW

**Minecraft:** 1.16.5
**Better Portals:** 0.3.2
**Forge:** 36.1.24
**Other mods:** .... Yes.... See log. :V  

**What happened:**
I had just eaten a forbidden fruit from enigmatic legacy and got hit with a bunch of negative buffs. My screen deformation setting was at 50%. _(the one that tints the screen green instead of making it go wavey in portals and nausea effects and such)_

I drank the milk bucket to purge effects, but crashed due to client rendering screen related issues with only reference pointing to better portals. 

Was gonna later take a redemption potion to get rid of the forbidden fruit permanent effect after a bit of testing but then this crash happened.

**Comment by yungnickyoung** [comment]
Seems to be the same root issue as #20 . Gonna be redirecting all discussion into there.

**Comment by Darkmega18** [comment]
[Roger-roger](https://tenor.com/view/roger-roger-roger-roger-that-copy-that-robots-gif-5912820)
