### ISSUE TITLE
Crash soon after entering Nether

### ISSUE THREAD

**Issue by Inqie** [YUNG-GANG/YUNGs-Better-Portals#38]
Unfortunately I couldn't narrow down the cause after several hours of troubleshooting. 

[crash-2021-08-07_19.08.58-client](https://pastebin.com/88cm1MPr)

**System Info:**
Minecraft Version: 1.16.5
Forge Version: 36.2.2
Better Portals Version: 0.3.7
Java Version: 11.0.11 64bit
CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics
GPU: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

**Comment by yungnickyoung** [comment]
Fixed in v0.3.8.
