### ISSUE TITLE
Console spamming "unable to find dimension name, using default portal color" at start of world

### ISSUE THREAD

**Issue by noolaan** [YUNG-GANG/YUNGs-Better-Portals#4]
As soon as I enter a singleplayer world, the console begins spamming
`ERROR: Unable to get dimension name! Using default portal color...`

Unfortuately there are a lot of mods here, but maybe it will be helpful.
https://paste.ee/p/qsNoy

**Comment by yungnickyoung** [comment]
This is an issue with Optifine doing weird stuff with modded fluids. It also causes the fluid to render improperly, looking identical to lava instead of having a purple color. I'm working on a fix.

**Comment by yungnickyoung** [comment]
Should be fixed in v0.2.1.
