### ISSUE TITLE
1.16.4-0.3.8 Dedicated Server Crash on Feature Placement

### ISSUE THREAD

**Issue by kreezxil** [YUNG-GANG/YUNGs-Better-Portals#41]
Server Crash Report: https://hastebin.com/ohozawuric.rb
Server Latest Log: https://hastebin.com/iboguqohot.sql

MC: 1.16.5
Forge: 36.2.4

In pack: (my pack) https://www.curseforge.com/minecraft/modpacks/world-of-dragons-ii

**Happened while exploring**

Possible related issues: #21, #26

**Comment by kreezxil** [comment]
oh wow, I just posted on to the end of #45, @yungnickyoung have you looked into this at all?

**Comment by yungnickyoung** [comment]
Will move the conversation to #45.
