### ISSUE TITLE
[Suggestion] Make Dimensional Rifts affected by Generate Structures option on world creation.

### ISSUE THREAD

**Issue by ghost** [YUNG-GANG/YUNGs-Better-Portals#42]
When you hit [More World Options] when making a new world, there's a toggle for Generate Structures.

It would be useful if Dimensional Rifts/Plasma Pools were effected by the toggle, such that they wouldn't generate when it's turned on.

Thank you for the cool mod!

**Comment by yungnickyoung** [comment]
This is functionally equivalent to the first part of #24 , so gonna mark this as duplicate.

Glad you like the mod :)
