### ISSUE TITLE
Crash when using a Rift

### ISSUE THREAD

**Issue by jlaw21** [YUNG-GANG/YUNGs-Better-Portals#43]
Yung's Version: 1.16.4-Forge-12
Server Crash Log: https://pastebin.com/u2XfV9xY
Client Crash Log: https://pastebin.com/k35yvqk5
Latest Log:
[latest.log](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/7290715/latest.log)

Unfortuantely, world is no longer playable. Could possibly be because I have the spawn chance cranked up so you have the search for the portals and this may have caused an issue with how they link up? I also have these rifts and monoliths NOT in the nether.

Thanks!

**Comment by jlaw21** [comment]
Nevermind, I forgot to add the spawn platform, so it had no clue where to put me.  I think. Please confirm that this would indeed cause the problem?

**Comment by yungnickyoung** [comment]
Yeah, that looks to be the problem. It was attempting to placea null block for the spawn platform.
