### ISSUE TITLE
Underground Rift Not Working

### ISSUE THREAD

**Issue by Helicaste** [YUNG-GANG/YUNGs-Better-Portals#52]
Hello,

I would like to preface this with the cardinal sin of bug reporting minecraft mods; I am playing in a modpack. To my (incredibly incomplete) knowledge, none of the mods in the pack conflict with Better Portals, but I have no _actual_ idea if it's a conflict of mods or a conflict in my head. I don't expect a magic solution from thin air.

My "bug" is that I jump into the rift fluid, sit there while the portal sound and screen effect play out, and then do not get shunted into the Nether. I am unsure what logs I would/should/could look at to help with this issue.

This issue is primarily to ask this question to make sure i'm using the Rifts correctly, all you need to do to activate them is just jump in, right?

**Comment by yungnickyoung** [comment]
Yeah, all you should need to do is jump in. If you want you can recreate the issue and then upload your latest.log here and I can take a look to see if it indicates anything. Other than that, you can try removing mods on a new save file until the rift works to identify the conflicting mod.

**Comment by Helicaste** [comment]
I have identified the conflicting mod, and thankfully fixed it due to your portals' configurability. Very epic, 10/10 backend.
