### ISSUE TITLE
Teleporting other entities than the player?

### ISSUE THREAD

**Issue by AzureMonument** [YUNG-GANG/YUNGs-Better-Portals#8]
So, I've recently downloaded this mod and added it to my (rather large) modpack. Now, for the first time I've forayed into the nether, and on my journey I encountered and tamed an adorable foxhound from the quark mod.
![2021-02-15_13 58 57](https://user-images.githubusercontent.com/43318292/107987900-e3a8bd80-6f9c-11eb-8039-decdd47b87b7.png)

Now, eventually I manage to find a monolith (didn't realize their beams would be black when unnactivated at first), and even a fortress right next to it! After a brief foray into said fortress I took the monolith, but I encountered an issue. I couldn't get my foxhound to teleport with me! I eventually took it (after writing down the coords of course) and returned to the overworld, but lo and behold, my foxhound was nowhere to be found. 

I eventually made my way back to my base (didn't realize that the monolith also respected dimension shifting, I was like a thousand something blocks away... thank the waystone mod + towers of the wild). I then took the portal back to the nether and made my way to the monolith. Luckily, when I re-entered the nether my foxhound immediately teleported to me. Anyway, so after I got to the monolith I picked up the returner block and the gold and then made my way back to where my portal brings me to the nether and set up there and attempted to push my foxhound into the beam.

![2021-02-15_14 43 24](https://user-images.githubusercontent.com/43318292/107988198-7c3f3d80-6f9d-11eb-92cc-9bd3b4b2483e.png)
This is 30 seconds after I managed to do so.

Distraught I took the portal to the overworld and noticed something odd. One of the mods I have is the GUI Followers mod, that lets me see a list of my followers, the distance to them, and their health. While in the overworld, despite my foxhound being nowhere to be found, I still had the gui. Not only that, but my foxhound was only about a hundred blocks away!

![2021-02-15_14 45 39](https://user-images.githubusercontent.com/43318292/107988332-bf011580-6f9d-11eb-9ca9-71b4b996dabc.png)

I then went towards the area where it said my foxhound was, but I quickly realized something.

![2021-02-15_14 46 14](https://user-images.githubusercontent.com/43318292/107988378-de983e00-6f9d-11eb-84d8-e619a0be321c.png)
![2021-02-15_14 46 15](https://user-images.githubusercontent.com/43318292/107988431-fd96d000-6f9d-11eb-80dc-978fc9d22f40.png)

It was taking the nether coords I left my foxhound at! In these images you can see the distance unit is leading me into empty air (first image is me on the ground, the second is me jumping. This means my foxhound is still in the nether, and I'm no closer to bringing it to the overworld. *sadness*. I don't know if this is a bug or intended, but either way it is saddening. And also prevents you from getting the achievement Uneasy Alliance, now that I think about it...

Anyway. I'm going back to the nether to let my foxhound lay down at least, and then probably submit a bug report to the GUI followers mod about pets not respecting dimensions. It'd be nice if there was some way to get it to the overworld. Thanks for the mod~♫

**Comment by AzureMonument** [comment]
Oh, one thing I noticed after I moved the monolith to about the same position as my portal (though somewhat unrelated)- you can be teleported directly into the nether portal from the monolith. Not sure if that's intended, but I thought I'd at least make you aware.

**Comment by AzureMonument** [comment]
![2021-02-15_15 11 11](https://user-images.githubusercontent.com/43318292/107989461-63845700-6fa0-11eb-83e3-c52f0e26f8c9.png)
![2021-02-15_15 11 17](https://user-images.githubusercontent.com/43318292/107989464-65e6b100-6fa0-11eb-8e25-3c43c1cf9227.png)

New info. So when I return to the nether and make my foxhound stand, I get two entities in the follower GUI. I beleive this means that the portal duplicated my foxhounds entity data? Or something along those lines as I still get the extra dataset while in the nether (maybe the entity data becomes dimensionless?)

I don't really know what to make of this, tbh.

**Comment by yungnickyoung** [comment]
It's just an oversight on my part that non-player entities cannot teleport with the Monolith. I'll add that in a future version.

The stuff regarding the follower GUI is likely a bug on their part - I currently have absolutely no non-player entity teleport logic implemented for Monoliths, so all that happens when it enters the beam is it floats up. There's no bug regarding teleportation since the logic for it doesn't exist lol.

The Monolith teleporting you to Dimensional Plasma is intended. Monoliths will teleport you into the nearest dimensional plasma, if any is nearby. This is what allows for players to have a reliable two-way passage to/from the Nether at their base.

**Comment by AzureMonument** [comment]
Thanks. I've already submitted a bug report to the GUI followers~
Good to know the dimensional plasma is purposeful.

Good luck coding, and thanks for the mod~

If I may post a suggestion; It might be easier on the player that tamed mobs simply teleport to the dimension whenever they're following the player when the player teleports.
